/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/player`; params?: Router.UnknownInputParams; } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/browse` | `/browse`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mylist` | `/mylist`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/country/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/genre/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/list/[type]`, params: Router.UnknownInputParams & { type: string | number; } } | { pathname: `/movie/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/tv/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/player`; params?: Router.UnknownOutputParams; } | { pathname: `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/browse` | `/browse`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mylist` | `/mylist`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/country/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/genre/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/list/[type]`, params: Router.UnknownOutputParams & { type: string; } } | { pathname: `/movie/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/tv/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/player${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/browse${`?${string}` | `#${string}` | ''}` | `/browse${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mylist${`?${string}` | `#${string}` | ''}` | `/mylist${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/player`; params?: Router.UnknownInputParams; } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/browse` | `/browse`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mylist` | `/mylist`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | `/country/${Router.SingleRoutePart<T>}` | `/genre/${Router.SingleRoutePart<T>}` | `/list/${Router.SingleRoutePart<T>}` | `/movie/${Router.SingleRoutePart<T>}` | `/tv/${Router.SingleRoutePart<T>}` | { pathname: `/country/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/genre/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/list/[type]`, params: Router.UnknownInputParams & { type: string | number; } } | { pathname: `/movie/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/tv/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
